version: '3.8'

services:
  chess-app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://chessuser:chesspass@postgres:5432/chessdb
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - ./data:/app/data

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: chessdb
      POSTGRES_USER: chessuser
      POSTGRES_PASSWORD: chesspass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: