"""Add telegram_chat_id column

Revision ID: 487d1c81c3a6
Revises: 
Create Date: 2026-02-03 19:16:01.585168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487d1c81c3a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('telegram_chat_id')

    # ### end Alembic commands ###
